tinymce.addI18n('af_ZA',{
"Redo": "Herdoen",
"Undo": "Ongedaan maak",
"Cut": "Sny",
"Copy": "Kopieer",
"Paste": "Plak",
"Select all": "Alles selekteer",
"New document": "Nuwe Dokument",
"Ok": "OK",
"Cancel": "Kanselleer",
"Visual aids": "Hulpmiddels",
"Bold": "Vetdruk",
"Italic": "Kursief",
"Underline": "Onderlyn",
"Strikethrough": "Deurhaal",
"Superscript": "Superskrif",
"Subscript": "Subskrif",
"Clear formatting": "Herstel Formateering",
"Align left": "Linksgerig",
"Align center": "Senteer",
"Align right": "Regsgerig",
"Justify": "Gerigstelling",
"Bullet list": "Opsommingsteken-lys",
"Numbered list": "Genommerde lys",
"Decrease indent": "Inkeping verklein",
"Increase indent": "Inkeping vergroot",
"Close": "Sluit",
"Formats": "Formate",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Jou webblaaier ondersteun nie toegang tot die knipbord nie. Gebruik asb. Ctrl+X\/C\/V",
"Headers": "Hooflyn-tekste",
"Header 1": "Hooflyn 1",
"Header 2": "Hooflyn 2",
"Header 3": "Hooflyn 3",
"Header 4": "Hooflyn 4",
"Header 5": "Hooflyn 5",
"Header 6": "Hooflyn 6",
"Headings": "Opskrifte",
"Heading 1": "Opskrif 1",
"Heading 2": "Opskrif 2",
"Heading 3": "Opskrif 3",
"Heading 4": "Opskrif 4",
"Heading 5": "Opskrif 5",
"Heading 6": "Opskrif 6",
"Preformatted": "Preformatted",
"Div": "Div",
"Pre": "Pre",
"Code": "Kode",
"Paragraph": "Paragraaf",
"Blockquote": "Aanhaling",
"Inline": "Inlyn",
"Blocks": "Blokke",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Die plak funksie is nou in plat-teks modus. Teks word ingevoeg sonder enige formateering, todat jy hierdie opsie wissel.",
"Fonts": "Fonts",
"Font Sizes": "Font Groote",
"Class": "Class",
"Browse for an image": "Browse for an image",
"OR": "OR",
"Drop an image here": "Drop an image here",
"Upload": "Upload",
"Block": "Block",
"Align": "Align",
"Default": "Verstek",
"Circle": "Sirkeltjie",
"Disc": "Balletjie",
"Square": "Vierkantjie",
"Lower Alpha": "Klein letters",
"Lower Greek": "Griekse letters",
"Lower Roman": "Romeinse syfers klein",
"Upper Alpha": "Hoofletters",
"Upper Roman": "Romeinse syfers groot",
"Anchor...": "Anchor...",
"Name": "Geen",
"Id": "Id",
"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "Id moet met 'n letter begin en kan slegs deur letters, koppeltekens, syfers, punte en onderstreep-karakters gevolg word.",
"You have unsaved changes are you sure you want to navigate away?": "Jy het ongestoorde wysigings op hierdier bladsy - is jy seker dat jy die bladsy wil verlaat?",
"Restore last draft": "Herstel die laatste konsep",
"Special characters...": "Special characters...",
"Source code": "Bron kode",
"Insert\/Edit code sample": "Voeg\/Redigeer voorbeeld-kode",
"Language": "Taal",
"Code sample...": "Code sample...",
"Color Picker": "Color Picker",
"R": "Rooi",
"G": "Groen",
"B": "Blou",
"Left to right": "Links na regs",
"Right to left": "Regs na links",
"Emoticons...": "Emoticons...",
"Metadata and Document Properties": "Metadata and Document Properties",
"Title": "Titel",
"Keywords": "Sleutelwoorde",
"Description": "Beskrywing",
"Robots": "Robotte",
"Author": "Outeur",
"Encoding": "Enkodeering",
"Fullscreen": "Volskerm",
"Action": "Action",
"Shortcut": "Shortcut",
"Help": "Help",
"Address": "Address",
"Focus to menubar": "Focus to menubar",
"Focus to toolbar": "Focus to toolbar",
"Focus to element path": "Focus to element path",
"Focus to contextual toolbar": "Focus to contextual toolbar",
"Insert link (if link plugin activated)": "Insert link (if link plugin activated)",
"Save (if save plugin activated)": "Save (if save plugin activated)",
"Find (if searchreplace plugin activated)": "Find (if searchreplace plugin activated)",
"Plugins installed ({0}):": "Plugins installed ({0}):",
"Premium plugins:": "Premium plugins:",
"Learn more...": "Learn more...",
"You are using {0}": "You are using {0}",
"Plugins": "Plugins",
"Handy Shortcuts": "Handy Shortcuts",
"Horizontal line": "Horisontale lyn",
"Insert\/edit image": "Afbeelding invoeg\/bewerk",
"Image description": "Afbeelding bemskrywing",
"Source": "Bron",
"Dimensions": "Afmetings",
"Constrain proportions": "Behou verhoudings",
"General": "Algemeen",
"Advanced": "Gevorderd",
"Style": "Styl",
"Vertical space": "Vertikale Spasie",
"Horizontal space": "Horisontale Spasie",
"Border": "Rand",
"Insert image": "Afbeelding invoeg",
"Image...": "Image...",
"Image list": "Image list",
"Rotate counterclockwise": "Linksom draai",
"Rotate clockwise": "Regsom draai",
"Flip vertically": "Vertikaal weerspie\\u00ebl",
"Flip horizontally": "Horisontaal weerspie\\u00ebl",
"Edit image": "Bewerk afbeelding",
"Image options": "Afbeelding opsies",
"Zoom in": "Inzoem",
"Zoom out": "Uitzoem",
"Crop": "Afknip",
"Resize": "Grootte wysig",
"Orientation": "Orienteering",
"Brightness": "Helderheid",
"Sharpen": "Verskerp",
"Contrast": "Kontras",
"Color levels": "Kleurvlakke",
"Gamma": "Gamma",
"Invert": "Omkeer",
"Apply": "Toepas",
"Back": "Terug",
"Insert date\/time": "Voeg datum\/tyd in",
"Date\/time": "Datum\/tyd",
"Insert\/Edit Link": "Insert\/Edit Link",
"Insert\/edit link": "Skakel invoeg\/bewerk",
"Text to display": "Skakelteks",
"Url": "URL",
"Open link in...": "Open link in...",
"Current window": "Current window",
"None": "Geen",
"New window": "Nuwe Skerm",
"Remove link": "Verwyder skakel",
"Anchors": "Ankers",
"Link...": "Link...",
"Paste or type a link": "Plak of tik 'n skalel in",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Die URL lyk soos 'n eposadres. Wil jy die \"mailto:\" voorvoegsel byvoeg?",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Die URL verwys na 'n eksterne adres. Wil jy die \"http:\/\/\" voorvoegsel byvoeg?",
"Link list": "Link list",
"Insert video": "Video invoeg",
"Insert\/edit video": "Video invoeg\/bewerk",
"Insert\/edit media": "Media invoeg\/bewerk",
"Alternative source": "Alternatiewe bron",
"Alternative image URL": "Alternative image URL",
"Media poster (Image URL)": "Media poster (Image URL)",
"Paste your embed code below:": "Plak jou ingesluite kode hieronder in:",
"Embed": "Insluit",
"Media...": "Media...",
"Nonbreaking space": "Vaste spasie invoeg",
"Page break": "Nuwe Bladsy",
"Paste as text": "As teks plak",
"Preview": "Voorskou",
"Print...": "Print...",
"Save": "Stoor",
"Find": "Soek",
"Replace with": "Vervang Met",
"Replace": "Vervang",
"Replace all": "Vervang alles",
"Previous": "Previous",
"Next": "Volgende",
"Find and replace...": "Find and replace...",
"Could not find the specified string.": "Kon nie die gesoekde string vind nie",
"Match case": "Kassensitief",
"Find whole words only": "Find whole words only",
"Spell check": "Spell check",
"Ignore": "Ignoreer",
"Ignore all": "Ignoreer alles",
"Finish": "Einde",
"Add to Dictionary": "Voeg by woordeboek",
"Insert table": "Tabel invoeg",
"Table properties": "Tabel eienskappe",
"Delete table": "Skrap tabel",
"Cell": "Sel",
"Row": "Ry",
"Column": "Kolom",
"Cell properties": "Sel eienskappe",
"Merge cells": "Selle saamvoeg",
"Split cell": "Sel split",
"Insert row before": "Voeg nuwe ry boaan",
"Insert row after": "Voeg nuwe ry na",
"Delete row": "Verwyder ry",
"Row properties": "Ry eienskappe",
"Cut row": "Knip ry",
"Copy row": "Kopieer ry",
"Paste row before": "Plak ry vooraan",
"Paste row after": "Plak ry na",
"Insert column before": "Voeg kolom vooraan",
"Insert column after": "Voeg kolom na",
"Delete column": "Verwyder kolom",
"Cols": "Kolomme",
"Rows": "Rye",
"Width": "Wydte",
"Height": "Hoogte",
"Cell spacing": "Ruimte rondom sel",
"Cell padding": "Ruimte binnein sel",
"Show caption": "Show caption",
"Left": "Links",
"Center": "Middel",
"Right": "Regs",
"Cell type": "Sel tipe",
"Scope": "Bereik",
"Alignment": "Gerigdheid",
"H Align": "Horisontaal-gerigdheid",
"V Align": "Vertikaal-rerigdheid",
"Top": "Bo",
"Middle": "Middel",
"Bottom": "Onder",
"Header cell": "Kop Sel",
"Row group": "Ry Groep",
"Column group": "Kolom Groep",
"Row type": "Ry tipe",
"Header": "Kopteks",
"Body": "Tabel Inhoud",
"Footer": "Voetskrif",
"Border color": "Randkleur",
"Insert template...": "Insert template...",
"Templates": "Sjablone",
"Template": "Template",
"Text color": "Teks Kleur",
"Background color": "Agtergrond Kleur",
"Custom...": "Spesifiek...",
"Custom color": "Spesifieke Kleur",
"No color": "Geen Kleur",
"Remove color": "Remove color",
"Table of Contents": "Inhoudsopgawe",
"Show blocks": "Blokke vertoon",
"Show invisible characters": "Onsigbare karakters vertoon",
"Word count": "Word count",
"Words: {0}": "Woorde: {0}",
"{0} words": "{0} words",
"File": "L\u00eaer",
"Edit": "Wysig",
"Insert": "Invoeg",
"View": "Formaat",
"Format": "Formateer",
"Table": "Tabel",
"Tools": "Gereedskap",
"Powered by {0}": "Powered by {0}",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Ryk Teks Area. Druk ALT-F9 vir menu, ALT-F10 vir die nutsbalk, ALT-0 vir hulp.",
"Image title": "Image title",
"Border width": "Border width",
"Border style": "Border style",
"Error": "Error",
"Warn": "Warn",
"Valid": "Valid",
"To open the popup, press Shift+Enter": "To open the popup, press Shift+Enter",
"Rich Text Area. Press ALT-0 for help.": "Rich Text Area. Press ALT-0 for help.",
"System Font": "System Font",
"Failed to upload image: {0}": "Failed to upload image: {0}",
"Failed to load plugin: {0} from url {1}": "Failed to load plugin: {0} from url {1}",
"Failed to load plugin url: {0}": "Failed to load plugin url: {0}",
"Failed to initialize plugin: {0}": "Failed to initialize plugin: {0}",
"example": "example",
"Search": "Search",
"All": "All",
"Currency": "Currency",
"Text": "Text",
"Quotations": "Quotations",
"Mathematical": "Mathematical",
"Extended Latin": "Extended Latin",
"Symbols": "Symbols",
"Arrows": "Arrows",
"User Defined": "User Defined",
"dollar sign": "dollar sign",
"currency sign": "currency sign",
"euro-currency sign": "euro-currency sign",
"colon sign": "colon sign",
"cruzeiro sign": "cruzeiro sign",
"french franc sign": "french franc sign",
"lira sign": "lira sign",
"mill sign": "mill sign",
"naira sign": "naira sign",
"peseta sign": "peseta sign",
"rupee sign": "rupee sign",
"won sign": "won sign",
"new sheqel sign": "new sheqel sign",
"dong sign": "dong sign",
"kip sign": "kip sign",
"tugrik sign": "tugrik sign",
"drachma sign": "drachma sign",
"german penny symbol": "german penny symbol",
"peso sign": "peso sign",
"guarani sign": "guarani sign",
"austral sign": "austral sign",
"hryvnia sign": "hryvnia sign",
"cedi sign": "cedi sign",
"livre tournois sign": "livre tournois sign",
"spesmilo sign": "spesmilo sign",
"tenge sign": "tenge sign",
"indian rupee sign": "indian rupee sign",
"turkish lira sign": "turkish lira sign",
"nordic mark sign": "nordic mark sign",
"manat sign": "manat sign",
"ruble sign": "ruble sign",
"yen character": "yen character",
"yuan character": "yuan character",
"yuan character, in hong kong and taiwan": "yuan character, in hong kong and taiwan",
"yen\/yuan character variant one": "yen\/yuan character variant one",
"Loading emoticons...": "Loading emoticons...",
"Could not load emoticons": "Could not load emoticons",
"People": "People",
"Animals and Nature": "Animals and Nature",
"Food and Drink": "Food and Drink",
"Activity": "Activity",
"Travel and Places": "Travel and Places",
"Objects": "Objects",
"Flags": "Flags",
"Characters": "Characters",
"Characters (no spaces)": "Characters (no spaces)",
"Error: Form submit field collision.": "Error: Form submit field collision.",
"Error: No form element found.": "Error: No form element found.",
"Update": "Update",
"Color swatch": "Color swatch",
"Turquoise": "Turquoise",
"Green": "Green",
"Blue": "Blue",
"Purple": "Purple",
"Navy Blue": "Navy Blue",
"Dark Turquoise": "Dark Turquoise",
"Dark Green": "Dark Green",
"Medium Blue": "Medium Blue",
"Medium Purple": "Medium Purple",
"Midnight Blue": "Midnight Blue",
"Yellow": "Yellow",
"Orange": "Orange",
"Red": "Red",
"Light Gray": "Light Gray",
"Gray": "Gray",
"Dark Yellow": "Dark Yellow",
"Dark Orange": "Dark Orange",
"Dark Red": "Dark Red",
"Medium Gray": "Medium Gray",
"Dark Gray": "Dark Gray",
"Black": "Black",
"White": "White",
"Switch to or from fullscreen mode": "Switch to or from fullscreen mode",
"Open help dialog": "Open help dialog",
"history": "history",
"styles": "styles",
"formatting": "formatting",
"alignment": "alignment",
"indentation": "indentation",
"permanent pen": "permanent pen",
"comments": "comments",
"Anchor": "Anker",
"Special character": "Spesiaale karakter",
"Color": "Kleur",
"Emoticons": "Emoticons",
"Document properties": "Dokument eienskappe",
"Image": "Afbeelding",
"Insert link": "Skakel invoeg",
"Link": "Skakel",
"Target": "Teiken",
"Media": "Media",
"Poster": "Plakaat",
"Print": "Druk",
"Whole words": "Hele woorde",
"Find and replace": "Soek en vervang",
"Prev": "Vorige",
"Spellcheck": "Toets spelling",
"Caption": "Onderskrif",
"Insert template": "Sjabloon invoeg"
});